isic:
    resource: "@ISICBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
login:
    path:       /login
    defaults: { _controller: ISICBundle:Security:login}
user_registration:
    path:     /register
    defaults: { _controller: ISICBundle:Security:register }
edit_user:
    path:     /edit_user/{userId}
    defaults: { _controller: ISICBundle:Security:editUser }
list_users:
    path:     /list_users
    defaults: { _controller: ISICBundle:Security:listUsers }

role_create:
    path:     /role_create
    defaults: { _controller: ISICBundle:Security:roleCreate }
edit_role:
    path:     /edit_role/{roleId}
    defaults: { _controller: ISICBundle:Security:editRole }
list_roles:
    path:     /list_roles
    defaults: { _controller: ISICBundle:Security:listRoles }
BCCResqueBundle:
    resource: "@BCCResqueBundle/Resources/config/routing.xml"
    prefix:   /resque
   
logout:
    path: /logout
generate_xml:
    path:     /generate_xml
    defaults: { _controller: ISICBundle:XML:generateXML }    
