isic:
    resource: "@ISICBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
login:
    path:       /login
    defaults: { _controller: ISICBundle:Security:login}