isic:
    resource: "@ISICBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
login:
    path:       /login
    defaults: { _controller: ISICBundle:Security:login}
user_registration:
    path:     /register
    defaults: { _controller: ISICBundle:Security:register }
edit_user:
    path:     /edit_user/{userId}
    defaults: { _controller: ISICBundle:Security:editUser }
list_users:
    path:     /list_users
    defaults: { _controller: ISICBundle:Security:listUsers }

role_create:
    path:     /role_create
    defaults: { _controller: ISICBundle:Security:roleCreate }
edit_role:
    path:     /edit_role/{roleId}
    defaults: { _controller: ISICBundle:Security:editRole }
list_roles:
    path:     /list_roles
    defaults: { _controller: ISICBundle:Security:listRoles }
   
logout:
    path: /logout
generate_xml:
    path:     /generate_xml
    defaults: { _controller: ISICBundle:XML:generateXML } 
generate_file:
    path:     /generate_file
    defaults: { _controller: ISICBundle:GenerateFile:generateFile } 
search_xml:
    path:     /search_xml
    defaults: { _controller: ISICBundle:Archive:searchXML }   
get_xml:
    path:     /get_xml/{archiveId}
    defaults: { _controller: ISICBundle:Archive:resultArchive }    
search_data:
    path:     /search_data
    defaults: { _controller: ISICBundle:EGNArchive:searchData }   
get_data:
    path:     /get_data/{archiveId}
    defaults: { _controller: ISICBundle:EGNArchive:resultData }    
