isic_homepage:
    path:     /
    defaults: { _controller: ISICBundle:Default:index }
isic_import:
    path: import
    defaults: { _controller: ISICBundle:Import:import }
egn_import:
    path: egn_import
    defaults: { _controller: ISICBundle:PersonalNumber:import }
