# автор Мария Пенелова
ISICBundle\Entity\Card:
    type: entity
    oneToMany:
    isics:
      targetEntity: Isic
      mappedBy: cardType
    table: card_type
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 250