ISICBundle\Entity\Isic:
    type: entity
    table: isic
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        IDWKeyColumn:
            type: integer
            nullable: true	
        IDWFirstNameBG:
            type: string
            length: 250
            nullable: true
        IDWFamilyNameBG:
            type: string
            length: 50
            nullable: true
        IDWFirstNameEN:
            type: string
            length: 250
            nullable: true
        IDWFamilyNameEN:
            type: string
            length: 250
            nullable: true
        IDWFacultyBG:
            type: string
            length: 250
            nullable: true
        IDWFacultyEN:
            typr: string
            length: 250
            nullable: true
        IDWClass:
            type: string
            length: 250
            nullable: true
        IDWFacultyNumber:
            type: string
            length: 250
            nullable: true
        IDWLID:
            type: string
            length: 50
            nullable: true
        IDWBarCodeInt:
            type: string
            length: 50
            nullable: true
        IDWBarCodeField:
            type: string
            length: 250
            nullable: true
        IDWLIDBack:
            type: string
            length: 250
            nullable: true
        IDWBarCodeIntBack:
            type: string
            length: 250
            nullable: true
        IDWBarCodeFieldBack:
            type: string
            length: 250
            nullable: true
        IDWPhoto:
            type: string
            length: 250
            nullable: true
        EGN:
            type: string
            length: 250
            nullable: true
        Birthdate:
            type: string
            length: 50
            nullable: true
        Specialty:
            type: string
            length: 250
            nullable: true
        ChipNumber:
            type: string
            length: 250
            nullable: true
        PhoneNumber:
            type: string
            length: 250
            nullable: true
        Email:
            type: string
            length: 250
            nullable: true
        Names:
            type: string
            length: 250
            nullable: true
        status:
            type: string
            length: 10
            nullable: true
        isPublished:
            type: boolean
            nullable: true
        importDate:
            type: datetime
                 
