ISICBundle\Entity\Permission:
    type: entity
    manyToMany:
      userRoles:
        targetEntity: Role
        mappedBy: permissions
    
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 100
        