ISICBundle\Entity\Role:
    type: entity
    manyToMany:
        permissions:
            targetEntity: Permission
            inversedBy: roles
            joinTable:
                name: role_permission
                joinColumns:
                    role_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    permission_id:
                        referencedColumnName: id
    manyToMany:
      users:
        targetEntity: User
        mappedBy: roles
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 100