ISICBundle\Entity\Role:
    type: entity
    manyToMany:
      permissions:
        targetEntity: Permission
        mappedBy: roles
    manyToMany:
      users:
        targetEntity: User
        mappedBy: roles
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 100