ISICBundle\Entity\Susi:
    type: entity
    table: susi
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 250
            nullable: true
        faculty:
            type: string
            length: 250
            nullable: true 
        facultyNumber:
            type: string
            length: 10
            nullable: true 
        name:
            type: string
            length: 250
            nullable: true
        email:
            type: string
            length: 250
            nullable: true 
        phoneNumber:
            type: string
            length: 25
            nullable: true 
        egn:
            type: string
            length: 25
            nullable: true 
        addressCity:
            type: string
            length: 250
            nullable: true 
        addressStreet:
            type: string
            length: 250
            nullable: true  
        genderName:
            type: string
            length: 2
            nullable: true 
        postCode:
            type: string
            length: 7
            nullable: true 
        birthDate:
            type: string
            length: 15
            nullable: true                   
