ISICBundle\Entity\User:
    type: entity
    table: app_users
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        username:
            type: string
            length: 100
        password:
            type: string
            length: 1000
        email:
            type: string
            length: 255
        isActive:
            type: boolean
