ISICBundle\Entity\User:
    type: entity
    table: app_users
    manyToMany:
        userRoles:
            targetEntity: Role
            inversedBy: users
            joinTable:
                name: users_roles
                joinColumns:
                    user_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    role_id:
                        referencedColumnName: id
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        username:
            type: string
            length: 100
        password:
            type: string
            length: 1000
        email:
            type: string
            length: 255
        isActive:
            type: boolean
        roles:
            type: string    
            length: 255